version: "3.9"

services:

  user-service:
    build:
      context: ./user-service
    networks:
      - backend

  product-service:
    build:
      context: ./product-service
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - user-service
      - product-service
    networks:
      - backend

networks:

  backend:
    driver: bridge
