events {}

http {

    upstream users_backend {

        server user-service:3000;

    }

    upstream products_backend {

        server product-service:3000;

    }

    server {

        listen 80;

        location /users {

            proxy_pass http://users_backend/;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

        }

        location /products {

            proxy_pass http://products_backend/;

            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;

        }

    }

}